version: "3.8"
services:
  redis:
    container_name: 'redis'
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis.config:/usr/local/etc/redis/redis.conf
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

